### ISSUE TITLE
About Licence

### ISSUE THREAD

**Issue by jack17529** [victorlaurentiu/MazeGenerator_graphsUnioning#4]
Please put a licence(GPL Licence) on the repository. I am thinking of using modification of your algorithm in one of my repository. I will credit you for that :)

**Comment by victor-mlai** [comment]
Hi, I've added a MIT licence if that's ok.
Also, I've commited some refactoring in the code because the code was way too messy for me to let it that way :)
And yes, please notice me about the work you've done with it.. Would love to see it :)
